services:
  web: 
    image: skyface753/skyblog-web
    build:
      context: ./skyface-web
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
  backend:
    image: skyface753/skyblog-backend
    build:
      context: ./skyface-backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./files:/usr/src/app/uploaded-files
    environment:
      - FRONTEND_URL=https://www.skyface.de
  # web:
  #   image: skyface753/skyblog-web
  #   ports:
  #     - "3000:3000"
  # backend:
  #   image: skyface753/skyblog-backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FRONTEND_URL=https://www.skyface.de
      

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db

  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8092:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin