services:
  web: 
    image: skyface753/skyblog
    build:
      context: ./skyface-backend
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./files:/usr/src/app/uploaded-files
    environment:
      - FRONTEND_URL=${FRONTEND_URL:-https://www.skyface.de}
      - JWT_SECRET=${JWT_SECRET:-secret}
      - JWT_ROUNDS=${JWT_ROUNDS:-10}
    restart: always

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db

  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8092:8081
  #   environment:
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=admin
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=admin