services:
  web:
    image: skyface753/skyblog-web
    ports:
      - "3000:3000"
  backend:
    image: skyface753/skyblog-backend
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_URL=http://skyface.de:3000

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8092:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/